; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_A]
platform = atmelavr
board = uno
framework = arduino
upload_port = COM7
monitor_port = COM7
build_src_filter = +<board_A-remote/>  ; 告訴總包商：只拿 board_A 資料夾裡的程式來編譯
lib_deps = 
    arduino-libraries/Servo @ ^1.2.1  ; 這行會自動下載官方的 Servo 函式庫
    z3t0/IRremote @ ^4.3.1  ; 這行就是紅外線的函式庫
; 記得要跟在env下面不要空行

[env:arduino_B]
platform = atmelavr
board = uno
framework = arduino
upload_port = COM5
monitor_port = COM5
build_src_filter = +<board_B/>  ; 告訴總包商：只拿 board_B 資料夾裡的程式來編譯
lib_deps = 
    arduino-libraries/Servo @ ^1.2.1  ; 這行會自動下載官方的 Servo 函式庫
    z3t0/IRremote @ ^4.3.1  ; 這行就是紅外線的函式庫
; 記得要跟在env下面不要空行